var express = require('express');
var router = express.Router();

/* GET pokemon wiki page. */
router.get('/', function(req, res, next) {
  const allPokemons = [
    { number: 650, name: 'Chespin', category: 'Pokémon Spiny Nut', type: ['Grama'], height: '0,4 m', weight: '9,0 kg', abilities: ['Overgrow', 'Bulletproof (Hidden)'], description: 'Chespin tem espinhos protetores. É muito corajoso e protetor.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/650.png' },
    { number: 651, name: 'Quilladin', category: 'Pokémon Spiny Armor', type: ['Grama'], height: '0,7 m', weight: '29,0 kg', abilities: ['Overgrow', 'Bulletproof (Hidden)'], description: 'Quilladin evoluiu de Chespin.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/651.png' },
    { number: 652, name: 'Chesnaught', category: 'Pokémon Spiny Armor', type: ['Grama', 'Lutador'], height: '1,6 m', weight: '90,0 kg', abilities: ['Overgrow', 'Bulletproof (Hidden)'], description: 'Chesnaught é a forma final de Chespin.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/652.png' },
    { number: 653, name: 'Fennekin', category: 'Pokémon Fox', type: ['Fogo'], height: '0,4 m', weight: '9,4 kg', abilities: ['Blaze', 'Magician (Hidden)'], description: 'Fennekin é uma raposa que cospe fogo. É muito inteligente e elegante.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/653.png' },
    { number: 654, name: 'Braixen', category: 'Pokémon Fox', type: ['Fogo'], height: '1,0 m', weight: '14,5 kg', abilities: ['Blaze', 'Magician (Hidden)'], description: 'Braixen evoluiu de Fennekin.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/654.png' },
    { number: 655, name: 'Delphox', category: 'Pokémon Fox', type: ['Fogo', 'Psíquico'], height: '1,5 m', weight: '39,0 kg', abilities: ['Blaze', 'Magician (Hidden)'], description: 'Delphox é a forma final de Fennekin.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/655.png' },
    { number: 656, name: 'Froakie', category: 'Pokémon Bubble Frog', type: ['Água'], height: '0,3 m', weight: '7,0 kg', abilities: ['Torrent', 'Protean (Hidden)'], description: 'Froakie é um sapo ninja que muda seu tipo. É muito ágil.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/656.png' },
    { number: 657, name: 'Frogadier', category: 'Pokémon Bubble Frog', type: ['Água'], height: '0,6 m', weight: '10,9 kg', abilities: ['Torrent', 'Protean (Hidden)'], description: 'Frogadier evoluiu de Froakie.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/657.png' },
    { number: 658, name: 'Greninja', category: 'Pokémon Ninja', type: ['Água', 'Sombrio'], height: '1,5 m', weight: '40,0 kg', abilities: ['Torrent', 'Protean (Hidden)'], description: 'Greninja é a forma final de Froakie.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png' },
    { number: 659, name: 'Bunnelby', category: 'Pokémon Digging', type: ['Normal'], height: '0,4 m', weight: '5,0 kg', abilities: ['Pickup', 'Cheek Pouch', 'Huge Power (Hidden)'], description: 'Bunnelby escava buracos. É muito trabalhador.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/659.png' },
    { number: 660, name: 'Diggersby', category: 'Pokémon Digging', type: ['Normal', 'Terra'], height: '1,0 m', weight: '42,4 kg', abilities: ['Pickup', 'Cheek Pouch', 'Huge Power (Hidden)'], description: 'Diggersby evoluiu de Bunnelby.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/660.png' },
    { number: 661, name: 'Fletchling', category: 'Pokémon Tiny Robin', type: ['Normal', 'Voador'], height: '0,3 m', weight: '1,7 kg', abilities: ['Big Pecks', 'Gale Wings (Hidden)'], description: 'Fletchling é um passarinho corajoso. Evolui para um pássaro majestoso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/661.png' },
    { number: 662, name: 'Fletchinder', category: 'Pokémon Ember', type: ['Fogo', 'Voador'], height: '0,7 m', weight: '16,0 kg', abilities: ['Flame Body', 'Gale Wings (Hidden)'], description: 'Fletchinder evoluiu de Fletchling.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/662.png' },
    { number: 663, name: 'Talonflame', category: 'Pokémon Scorching', type: ['Fogo', 'Voador'], height: '1,2 m', weight: '24,5 kg', abilities: ['Flame Body', 'Gale Wings (Hidden)'], description: 'Talonflame é a forma final de Fletchling.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/663.png' },
    { number: 664, name: 'Scatterbug', category: 'Pokémon Scatterdust', type: ['Inseto'], height: '0,3 m', weight: '2,5 kg', abilities: ['Shield Dust', 'Compound Eyes', 'Friend Guard (Hidden)'], description: 'Scatterbug libera pó quando ameaçado. Evolui baseado na forma.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/664.png' },
    { number: 665, name: 'Spewpa', category: 'Pokémon Scatterdust', type: ['Inseto'], height: '0,3 m', weight: '8,4 kg', abilities: ['Shed Skin', 'Friend Guard (Hidden)'], description: 'Spewpa evoluiu de Scatterbug.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/665.png' },
    { number: 666, name: 'Vivillon', category: 'Pokémon Scale', type: ['Inseto', 'Voador'], height: '1,2 m', weight: '17,0 kg', abilities: ['Shield Dust', 'Compound Eyes', 'Friend Guard (Hidden)'], description: 'Vivillon é a forma final de Scatterbug.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666.png' },
    { number: 667, name: 'Litleo', category: 'Pokémon Lion Cub', type: ['Fogo', 'Normal'], height: '0,6 m', weight: '13,5 kg', abilities: ['Rivalry', 'Unnerve', 'Moxie (Hidden)'], description: 'Litleo é um leão bebê que cospe fogo. É muito orgulhoso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/667.png' },
    { number: 668, name: 'Pyroar', category: 'Pokémon Royal', type: ['Fogo', 'Normal'], height: '1,5 m', weight: '81,5 kg', abilities: ['Rivalry', 'Unnerve', 'Moxie (Hidden)'], description: 'Pyroar é a forma final de Litleo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/668.png' },
    { number: 669, name: 'Flabébé', category: 'Pokémon Single Bloom', type: ['Fada'], height: '0,1 m', weight: '0,1 kg', abilities: ['Flower Veil', 'Symbiosis (Hidden)'], description: 'Flabébé vive dentro de flores. É muito gracioso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/669.png' },
    { number: 670, name: 'Floette', category: 'Pokémon Single Bloom', type: ['Fada'], height: '0,2 m', weight: '0,9 kg', abilities: ['Flower Veil', 'Symbiosis (Hidden)'], description: 'Floette evoluiu de Flabébé.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/670.png' },
    { number: 671, name: 'Florges', category: 'Pokémon Garden', type: ['Fada'], height: '1,1 m', weight: '10,0 kg', abilities: ['Flower Veil', 'Symbiosis (Hidden)'], description: 'Florges é a forma final de Flabébé.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/671.png' },
    { number: 672, name: 'Skiddo', category: 'Pokémon Mount', type: ['Grama'], height: '0,9 m', weight: '31,0 kg', abilities: ['Sap Sipper', 'Grass Pelt (Hidden)'], description: 'Skiddo carrega pessoas nas costas. É muito forte e gentil.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/672.png' },
    { number: 673, name: 'Gogoat', category: 'Pokémon Mount', type: ['Grama'], height: '1,7 m', weight: '91,0 kg', abilities: ['Sap Sipper', 'Grass Pelt (Hidden)'], description: 'Gogoat evoluiu de Skiddo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/673.png' },
    { number: 674, name: 'Pancham', category: 'Pokémon Playful', type: ['Lutador'], height: '0,6 m', weight: '8,0 kg', abilities: ['Iron Fist', 'Mold Breaker', 'Scrappy (Hidden)'], description: 'Pancham treina para se tornar um mestre panda. É muito brincalhão.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/674.png' },
    { number: 675, name: 'Pangoro', category: 'Pokémon Daunting', type: ['Lutador', 'Sombrio'], height: '2,1 m', weight: '136,0 kg', abilities: ['Iron Fist', 'Mold Breaker', 'Scrappy (Hidden)'], description: 'Pangoro evoluiu de Pancham.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/675.png' },
    { number: 676, name: 'Furfrou', category: 'Pokémon Poodle', type: ['Normal'], height: '1,2 m', weight: '28,0 kg', abilities: ['Fur Coat', 'Fur Coat (Hidden)'], description: 'Furfrou tem pelos que podem ser cortados em estilos diferentes.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/676.png' },
    { number: 677, name: 'Espurr', category: 'Pokémon Restraint', type: ['Psíquico'], height: '0,3 m', weight: '3,5 kg', abilities: ['Keen Eye', 'Infiltrator', 'Own Tempo (Hidden)'], description: 'Espurr tem poderes psíquicos. Seu olhar pode causar dor de cabeça.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/677.png' },
    { number: 678, name: 'Meowstic', category: 'Pokémon Constraint', type: ['Psíquico'], height: '0,6 m', weight: '8,5 kg', abilities: ['Keen Eye', 'Infiltrator', 'Prankster (Hidden)'], description: 'Meowstic evoluiu de Espurr.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/678.png' },
    { number: 679, name: 'Honedge', category: 'Pokémon Sword', type: ['Aço', 'Fantasma'], height: '0,8 m', weight: '2,0 kg', abilities: ['No Guard'], description: 'Honedge é uma espada possuída por um espírito. É muito leal.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/679.png' },
    { number: 680, name: 'Doublade', category: 'Pokémon Sword', type: ['Aço', 'Fantasma'], height: '0,8 m', weight: '4,5 kg', abilities: ['No Guard'], description: 'Doublade evoluiu de Honedge.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/680.png' },
    { number: 681, name: 'Aegislash', category: 'Pokémon Royal Sword', type: ['Aço', 'Fantasma'], height: '1,7 m', weight: '53,0 kg', abilities: ['Stance Change'], description: 'Aegislash é a forma final de Honedge.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/681.png' },
    { number: 682, name: 'Spritzee', category: 'Pokémon Perfume', type: ['Fada'], height: '0,2 m', weight: '0,5 kg', abilities: ['Healer', 'Aroma Veil (Hidden)'], description: 'Spritzee libera perfumes doces. É muito fofo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/682.png' },
    { number: 683, name: 'Aromatisse', category: 'Pokémon Perfume', type: ['Fada'], height: '0,8 m', weight: '15,5 kg', abilities: ['Healer', 'Aroma Veil (Hidden)'], description: 'Aromatisse evoluiu de Spritzee.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/683.png' },
    { number: 684, name: 'Swirlix', category: 'Pokémon Cotton Candy', type: ['Fada'], height: '0,4 m', weight: '3,5 kg', abilities: ['Sweet Veil', 'Unburden (Hidden)'], description: 'Swirlix é feito de algodão doce. É muito doce e adorável.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/684.png' },
    { number: 685, name: 'Slurpuff', category: 'Pokémon Meringue', type: ['Fada'], height: '0,8 m', weight: '5,0 kg', abilities: ['Sweet Veil', 'Unburden (Hidden)'], description: 'Slurpuff evoluiu de Swirlix.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/685.png' },
    { number: 686, name: 'Inkay', category: 'Pokémon Revolving', type: ['Sombrio', 'Psíquico'], height: '0,4 m', weight: '3,5 kg', abilities: ['Contrary', 'Suction Cups', 'Infiltrator (Hidden)'], description: 'Inkay gira para hipnotizar. Precisa ser segurado de cabeça para baixo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/686.png' },
    { number: 687, name: 'Malamar', category: 'Pokémon Overturning', type: ['Sombrio', 'Psíquico'], height: '1,5 m', weight: '47,0 kg', abilities: ['Contrary', 'Suction Cups', 'Infiltrator (Hidden)'], description: 'Malamar evoluiu de Inkay.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/687.png' },
    { number: 688, name: 'Binacle', category: 'Pokémon Two-Handed', type: ['Rocha', 'Água'], height: '0,5 m', weight: '31,0 kg', abilities: ['Tough Claws', 'Sniper', 'Pickpocket (Hidden)'], description: 'Binacle tem duas mãos. É muito forte.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/688.png' },
    { number: 689, name: 'Barbaracle', category: 'Pokémon Collective', type: ['Rocha', 'Água'], height: '1,3 m', weight: '96,0 kg', abilities: ['Tough Claws', 'Sniper', 'Pickpocket (Hidden)'], description: 'Barbaracle evoluiu de Binacle.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/689.png' },
    { number: 690, name: 'Skrelp', category: 'Pokémon Mock Kelp', type: ['Veneno', 'Água'], height: '0,5 m', weight: '7,3 kg', abilities: ['Poison Point', 'Poison Touch', 'Adaptability (Hidden)'], description: 'Skrelp se disfarça de alga. Libera toxinas quando ameaçado.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/690.png' },
    { number: 691, name: 'Dragalge', category: 'Pokémon Mock Kelp', type: ['Veneno', 'Dragão'], height: '1,8 m', weight: '81,5 kg', abilities: ['Poison Point', 'Poison Touch', 'Adaptability (Hidden)'], description: 'Dragalge evoluiu de Skrelp.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/691.png' },
    { number: 692, name: 'Clauncher', category: 'Pokémon Water Gun', type: ['Água'], height: '0,5 m', weight: '8,3 kg', abilities: ['Mega Launcher'], description: 'Clauncher dispara água pressurizada. É muito preciso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/692.png' },
    { number: 693, name: 'Clawitzer', category: 'Pokémon Howitzer', type: ['Água'], height: '1,3 m', weight: '35,3 kg', abilities: ['Mega Launcher'], description: 'Clawitzer evoluiu de Clauncher.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/693.png' },
    { number: 694, name: 'Helioptile', category: 'Pokémon Generator', type: ['Elétrico', 'Normal'], height: '0,5 m', weight: '6,0 kg', abilities: ['Dry Skin', 'Sand Veil', 'Solar Power (Hidden)'], description: 'Helioptile gera eletricidade. É muito preguiçoso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/694.png' },
    { number: 695, name: 'Heliolisk', category: 'Pokémon Generator', type: ['Elétrico', 'Normal'], height: '1,0 m', weight: '21,0 kg', abilities: ['Dry Skin', 'Sand Veil', 'Solar Power (Hidden)'], description: 'Heliolisk evoluiu de Helioptile.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/695.png' },
    { number: 696, name: 'Tyrunt', category: 'Pokémon Royal Heir', type: ['Rocha', 'Dragão'], height: '0,8 m', weight: '26,0 kg', abilities: ['Strong Jaw', 'Sturdy (Hidden)'], description: 'Tyrunt é um fóssil vivo. É muito agressivo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/696.png' },
    { number: 697, name: 'Tyrantrum', category: 'Pokémon Despot', type: ['Rocha', 'Dragão'], height: '2,5 m', weight: '270,0 kg', abilities: ['Strong Jaw', 'Rock Head (Hidden)'], description: 'Tyrantrum evoluiu de Tyrunt.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/697.png' },
    { number: 698, name: 'Amaura', category: 'Pokémon Tundra', type: ['Rocha', 'Gelo'], height: '1,3 m', weight: '25,2 kg', abilities: ['Refrigerate', 'Snow Warning (Hidden)'], description: 'Amaura é um fóssil vivo. Controla o gelo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/698.png' },
    { number: 699, name: 'Aurorus', category: 'Pokémon Tundra', type: ['Rocha', 'Gelo'], height: '2,7 m', weight: '225,0 kg', abilities: ['Refrigerate', 'Snow Warning (Hidden)'], description: 'Aurorus evoluiu de Amaura.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/699.png' },
    { number: 700, name: 'Sylveon', category: 'Pokémon Intertwining', type: ['Fada'], height: '1,0 m', weight: '23,5 kg', abilities: ['Cute Charm', 'Pixilate (Hidden)'], description: 'Sylveon evoluiu de Eevee. É muito gracioso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/700.png' },
    { number: 701, name: 'Hawlucha', category: 'Pokémon Wrestling', type: ['Lutador', 'Voador'], height: '0,8 m', weight: '21,5 kg', abilities: ['Limber', 'Unburden', 'Mold Breaker (Hidden)'], description: 'Hawlucha é um lutador de wrestling. É muito ágil.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/701.png' },
    { number: 702, name: 'Dedenne', category: 'Pokémon Antenna', type: ['Elétrico', 'Fada'], height: '0,2 m', weight: '2,2 kg', abilities: ['Cheek Pouch', 'Pickup', 'Plus (Hidden)'], description: 'Dedenne tem antenas elétricas. É muito fofo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/702.png' },
    { number: 703, name: 'Carbink', category: 'Pokémon Jewel', type: ['Rocha', 'Fada'], height: '0,3 m', weight: '5,7 kg', abilities: ['Clear Body', 'Sturdy (Hidden)'], description: 'Carbink é feito de joias. É muito duro.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/703.png' },
    { number: 704, name: 'Goomy', category: 'Pokémon Soft Tissue', type: ['Dragão'], height: '0,3 m', weight: '2,8 kg', abilities: ['Sap Sipper', 'Hydration', 'Gooey (Hidden)'], description: 'Goomy é feito de gosma. É muito pegajoso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/704.png' },
    { number: 705, name: 'Sliggoo', category: 'Pokémon Soft Tissue', type: ['Dragão'], height: '0,8 m', weight: '17,5 kg', abilities: ['Sap Sipper', 'Hydration', 'Gooey (Hidden)'], description: 'Sliggoo evoluiu de Goomy.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/705.png' },
    { number: 706, name: 'Goodra', category: 'Pokémon Dragon', type: ['Dragão'], height: '2,0 m', weight: '150,5 kg', abilities: ['Sap Sipper', 'Hydration', 'Gooey (Hidden)'], description: 'Goodra é a forma final de Goomy.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/706.png' },
    { number: 707, name: 'Klefki', category: 'Pokémon Key Ring', type: ['Aço', 'Fada'], height: '0,2 m', weight: '3,0 kg', abilities: ['Prankster', 'Magician (Hidden)'], description: 'Klefki guarda chaves. É muito travesso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/707.png' },
    { number: 708, name: 'Phantump', category: 'Pokémon Stump', type: ['Fantasma', 'Grama'], height: '0,4 m', weight: '7,0 kg', abilities: ['Natural Cure', 'Frisk', 'Harvest (Hidden)'], description: 'Phantump é um espírito de árvore. É muito solitário.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/708.png' },
    { number: 709, name: 'Trevenant', category: 'Pokémon Elder Tree', type: ['Fantasma', 'Grama'], height: '1,5 m', weight: '71,0 kg', abilities: ['Natural Cure', 'Frisk', 'Harvest (Hidden)'], description: 'Trevenant evoluiu de Phantump.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/709.png' },
    { number: 710, name: 'Pumpkaboo', category: 'Pokémon Pumpkin', type: ['Fantasma', 'Grama'], height: '0,4 m', weight: '5,0 kg', abilities: ['Pickup', 'Frisk', 'Insomnia (Hidden)'], description: 'Pumpkaboo é uma abóbora possuída. Varia de tamanho.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/710.png' },
    { number: 711, name: 'Gourgeist', category: 'Pokémon Pumpkin', type: ['Fantasma', 'Grama'], height: '0,9 m', weight: '12,5 kg', abilities: ['Pickup', 'Frisk', 'Insomnia (Hidden)'], description: 'Gourgeist evoluiu de Pumpkaboo.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/711.png' },
    { number: 712, name: 'Bergmite', category: 'Pokémon Ice Chunk', type: ['Gelo'], height: '1,0 m', weight: '99,5 kg', abilities: ['Own Tempo', 'Ice Body', 'Sturdy (Hidden)'], description: 'Bergmite é feito de gelo. É muito frio.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/712.png' },
    { number: 713, name: 'Avalugg', category: 'Pokémon Iceberg', type: ['Gelo'], height: '2,0 m', weight: '505,0 kg', abilities: ['Own Tempo', 'Ice Body', 'Sturdy (Hidden)'], description: 'Avalugg evoluiu de Bergmite.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/713.png' },
    { number: 714, name: 'Noibat', category: 'Pokémon Sound Wave', type: ['Voador', 'Dragão'], height: '0,5 m', weight: '8,0 kg', abilities: ['Frisk', 'Infiltrator', 'Telepathy (Hidden)'], description: 'Noibat emite ondas sonoras. É muito barulhento.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/714.png' },
    { number: 715, name: 'Noivern', category: 'Pokémon Sound Wave', type: ['Voador', 'Dragão'], height: '1,5 m', weight: '85,0 kg', abilities: ['Frisk', 'Infiltrator', 'Telepathy (Hidden)'], description: 'Noivern evoluiu de Noibat.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/715.png' },
    { number: 716, name: 'Xerneas', category: 'Pokémon Life', type: ['Fada'], height: '3,0 m', weight: '215,0 kg', abilities: ['Fairy Aura'], description: 'Xerneas é um dos lendários da sexta geração. Dá vida à natureza.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/716.png' },
    { number: 717, name: 'Yveltal', category: 'Pokémon Destruction', type: ['Sombrio', 'Voador'], height: '5,8 m', weight: '203,0 kg', abilities: ['Dark Aura'], description: 'Yveltal é um dos lendários da sexta geração. Traz destruição.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/717.png' },
    { number: 718, name: 'Zygarde', category: 'Pokémon Order', type: ['Dragão', 'Terra'], height: '5,0 m', weight: '305,0 kg', abilities: ['Aura Break', 'Power Construct (Hidden)'], description: 'Zygarde mantém o equilíbrio da natureza.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/718.png' },
    { number: 719, name: 'Diancie', category: 'Pokémon Jewel', type: ['Rocha', 'Fada'], height: '0,7 m', weight: '8,8 kg', abilities: ['Clear Body'], description: 'Diancie cria diamantes. É muito raro.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/719.png' },
    { number: 720, name: 'Hoopa', category: 'Pokémon Mischief', type: ['Psíquico', 'Fantasma'], height: '0,5 m', weight: '9,0 kg', abilities: ['Magician'], description: 'Hoopa pode teleportar objetos. Tem duas formas.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/720.png' },
    { number: 721, name: 'Volcanion', category: 'Pokémon Steam', type: ['Fogo', 'Água'], height: '1,7 m', weight: '195,0 kg', abilities: ['Water Absorb'], description: 'Volcanion controla vapor. É muito poderoso.', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/721.png' }
  ];

  const page = parseInt(req.query.page) || 1;
  const perPage = 12; // 12 Pokémon por página
  const totalPages = Math.ceil(allPokemons.length / perPage);
  const startIndex = (page - 1) * perPage;
  const endIndex = startIndex + perPage;
  const pokemons = allPokemons.slice(startIndex, endIndex);

  res.render('pokemon', { 
    title: 'Pokémon Wiki - Geração 6', 
    pokemons: pokemons,
    currentPage: page,
    totalPages: totalPages,
    hasNext: page < totalPages,
    hasPrev: page > 1,
    nextPage: page + 1,
    prevPage: page - 1
  });
});

module.exports = router;
